name = "partial-date"
type = "javascript"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2021-10-05"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"
#main = "./worker.js"

[site]
bucket = "./dist/spa"
entry-point = "./dist/worker"

